### ISSUE TITLE
Error when building the website [undefined class/module Digest::Base (ArgumentError)]

### ISSUE THREAD

**Issue by A-Alaa** [abeMedia/jekyll-pdf#18]
I get this error executing `bundle exec jekyll build`.  

```
/var/lib/gems/2.3.0/gems/sass-3.5.5/lib/sass/engine.rb:2:in `require': undefined class/module Digest::Base (ArgumentError)
	from /var/lib/gems/2.3.0/gems/sass-3.5.5/lib/sass/engine.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/sass-3.5.5/lib/sass.rb:99:in `require'
	from /var/lib/gems/2.3.0/gems/sass-3.5.5/lib/sass.rb:99:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-sass-converter-1.5.1/lib/jekyll/converters/scss.rb:3:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-sass-converter-1.5.1/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-sass-converter-1.5.1/lib/jekyll-sass-converter.rb:4:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-sass-converter-1.5.1/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/lib/jekyll.rb:198:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/lib/jekyll.rb:198:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/exe/jekyll:8:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.0/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
```
part of my Gemfile.lock: 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    bibtex-ruby (4.4.5)
      latex-decode (~> 0.0)
    citeproc (1.0.8)
      namae (~> 1.0)
    citeproc-ruby (1.1.8)
      citeproc (>= 1.0.4, < 2.0)
      csl (~> 1.4)
    colorator (1.1.0)
    concurrent-ruby (1.0.5)
    csl (1.5.0)
      namae (~> 1.0)
    csl-styles (1.0.1.8)
      csl (~> 1.0)
    digest (0.0.1)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.5)
    ffi (1.9.18)
    forwardable-extended (2.6.0)
    http_parser.rb (0.6.0)
    i18n (0.9.3)
      concurrent-ruby (~> 1.0)
    jekyll (3.7.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-feed (0.9.2)
      jekyll (~> 3.3)
    jekyll-pdf (0.1.7)
      digest (~> 0)
      jekyll (~> 3.1, >= 2.0)
      pdfkit (~> 0.8)
      wkhtmltopdf-installer (~> 0.12)
    jekyll-sass-converter (1.5.1)
      sass (~> 3.4)
    jekyll-scholar (5.11.0)
      bibtex-ruby (~> 4.0, >= 4.0.13)
      citeproc-ruby (~> 1.0)
      csl-styles (~> 1.0)
      jekyll (~> 3.0)
    jekyll-seo-tag (2.4.0)
      jekyll (~> 3.3)
    jekyll-watch (2.0.0)
      listen (~> 3.0)
```

**Comment by hoijui** [comment]
many people already fixed this in their forks, but as this repo is abanbndonned, you will not see a fix here.

see https://github.com/abeMedia/jekyll-pdf/issues/24 instead
